name: taurenmd
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - mdanalysis=2
    - mdtraj=1
    - openmm=7.6
    - matplotlib=3
    - numpy=1
    - pip
    - pip:
        - taurenmd
