name: taurenmd
channels:
    - conda-forge
    - omnia
    - defaults
dependencies:
    - python=3.7
    - mdanalysis=2
    - mdtraj
    - openmm
    - matplotlib=3
    - numpy=1
    - pip
    - pip:
        - taurenmd
