# tox git actions integration was taken from:
# https://github.com/ymyzk/tox-gh-actions/tree/e11a29e2e5c73b6e48f5d4ee379f903476d013c0
# Tests unittest pass, documentation builds, and package builds
name: test_py37

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: 3.7
        channels: conda-forge

    - name: Install dependencies
      run: |
        conda install pip setuptools wheel tox coverage[toml]
        #python -m pip install --upgrade pip setuptools wheel
        #pip install coverage[toml] virtualenv tox tox-gh-actions tox-conda
        # if you use tox-conda you can also add
        # tox-conda to the above list of dependencies

    - name: Test with tox
      run: tox -e py37
      #env:
      #  PLATFORM: ${{ matrix.platform }}

    # from https://github.com/codecov/codecov-action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
